config/routes.rb
Rails.application.routes.draw do

  resources :submissions, except: [:delete, :edit, :update]
  root 'welcome#index'

  resources :forms do 
    resources :questions, except: :index do
      resources :answers, except: [:edit, :update, :index]
    end
    resources :submissions, except: [:delete, :edit, :update, :show]
  end
  devise_for :users

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :form_id, :title, :answer_type
  validates :answer_type, inclusion:{in: ["text", "checkbox", "dropdown", "radio"]}
  
  has_many :answers
  belongs_to :form
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :set_form
  before_action :set_answer_types, only: [:new, :edit, :create, :update]

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to form_path(@form), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to form_path(@form), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to form_url(@form), notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end
    
    def set_form
      @form = Form.find(params[:form_id])
    end
    
    def set_answer_types
      @answer_types = ["text", "checkbox", "dropdown", "radio"]
    end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:form_id, :title, :answer_type)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for( @question, url: @question.new_record? ? form_questions_path(@form) : form_question_path(@form, @question)) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong>Form</strong><br>
    <%= f.label @form.title %>
	<%= f.hidden_field :form_id, value: @form.id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :answer_type %><br>
    <%= f.select :answer_type, options_for_select(@answer_types, @question.answer_type), prompt: "Select" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>


<%= link_to 'Back', form_path(@form) %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', form_path(@form) %>