config/routes.rb
Rails.application.routes.draw do

  resources :submissions, except: [:delete, :edit, :update]
  root 'welcome#index'

  resources :forms do 
    resources :questions, except: :index do
      resources :answers, except: [:edit, :update, :index]
    end
    resources :submissions, except: [:delete, :edit, :update, :show]
  end
  devise_for :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
 validates_presence_of :question_id, :text
  
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: [:destroy]
  before_action :set_form_and_question

  # GET /answers/new
  def new
    @answer = Answer.new
  end


  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to form_path(@form), notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to form_url(@form), notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end
    
    def set_form_and_question
      @form = Form.find(params[:form_id])
      @question = Question.find(params[:question_id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :text)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer, url: form_question_answers_path(@form, @question)) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong>Question</strong><br>
    <%= f.label @question.title %>
	<%= f.hidden_field :question_id, value: @question.id %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', form_path(@form) %>