config/routes.rb
Rails.application.routes.draw do

  resources :submissions, except: [:delete, :edit, :update]
  root 'welcome#index'

  resources :forms do 
    resources :questions, except: :index do
      resources :answers, except: [:edit, :update, :index]
    end
    resources :submissions, except: [:delete, :edit, :update, :show]
  end
  devise_for :users

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.where(user_id: current_user.id)
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:title, :user_id)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
	<%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form' %>

<%= link_to 'Back', form_path(@form) %>

app/views/forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.title %></td>
        <td><%= form.user_id %></td>
        <td><%= link_to 'Show', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @form.title %>
</p>

<div id="questions">
  <strong>Questions</strong>
  <table>
    <thead>
	  <tr>
		<th>id</th>
		<th>Title</th>
		<th>Answer Type</th>
		<th>Answers</th>
		<th></th>
		<th></th>
	  </tr>
	</thead>
	<tbody>
	<% @form.questions.each do |question| %>
		<tr>
			<td><%= question.id %></td>
			<td><%= question.title %></td>
			<td><%= question.answer_type %></td>
			<td>
			   <% if  question.answer_type != 'text' %>
			     <ul>
				   <% question.answers.each do |answer| %>
				     <li><%= answer.text %> <%= link_to 'Delete', form_question_answer_path(@form, question, answer), method: :delete  %></li>
				   <% end %>
				 </ul>
			   <% end %>
			</td>
			<td>
				<% if  question.answer_type != 'text' %>
					<%= link_to 'New Answer', new_form_question_answer_path(@form, question) %>
				<% end %>
			</td>
			<td><%= link_to 'Edit', edit_form_question_path(@form, question) %></td>
			<td><%= link_to 'Delete', form_question_path(@form, question), method: :delete  %></td>
		</tr>
	<% end %>
    </tbody>
  </table>
</div>

<p>Form submission Link: <%= new_form_submission_url(@form) %></p>
<%= link_to 'New Question', new_form_question_path(@form) %> 
<br>
<%= link_to 'veiw submissions', form_submissions_path(@form) %>
<br>
<%= link_to 'Edit', edit_form_path(@form) %> 
<br>
<%= link_to 'Back', forms_path %>